# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Child(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, url: str=None, rm_type: str=None):  # noqa: E501
        """Child - a model defined in Swagger

        :param url: The url of this Child.  # noqa: E501
        :type url: str
        :param rm_type: The rm_type of this Child.  # noqa: E501
        :type rm_type: str
        """
        self.swagger_types = {
            'url': str,
            'rm_type': str
        }

        self.attribute_map = {
            'url': 'url',
            'rm_type': 'rmType'
        }

        self._url = url
        self._rm_type = rm_type

    @classmethod
    def from_dict(cls, dikt) -> 'Child':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The child of this Child.  # noqa: E501
        :rtype: Child
        """
        return util.deserialize_model(dikt, cls)

    @property
    def url(self) -> str:
        """Gets the url of this Child.


        :return: The url of this Child.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """Sets the url of this Child.


        :param url: The url of this Child.
        :type url: str
        """

        self._url = url

    @property
    def rm_type(self) -> str:
        """Gets the rm_type of this Child.


        :return: The rm_type of this Child.
        :rtype: str
        """
        return self._rm_type

    @rm_type.setter
    def rm_type(self, rm_type: str):
        """Sets the rm_type of this Child.


        :param rm_type: The rm_type of this Child.
        :type rm_type: str
        """

        self._rm_type = rm_type
