# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2001(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, rm_id: str=None, available: bool=None):  # noqa: E501
        """InlineResponse2001 - a model defined in Swagger

        :param rm_id: The rm_id of this InlineResponse2001.  # noqa: E501
        :type rm_id: str
        :param available: The available of this InlineResponse2001.  # noqa: E501
        :type available: bool
        """
        self.swagger_types = {
            'rm_id': str,
            'available': bool
        }

        self.attribute_map = {
            'rm_id': 'rmId',
            'available': 'available'
        }

        self._rm_id = rm_id
        self._available = available

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.  # noqa: E501
        :rtype: InlineResponse2001
        """
        return util.deserialize_model(dikt, cls)

    @property
    def rm_id(self) -> str:
        """Gets the rm_id of this InlineResponse2001.


        :return: The rm_id of this InlineResponse2001.
        :rtype: str
        """
        return self._rm_id

    @rm_id.setter
    def rm_id(self, rm_id: str):
        """Sets the rm_id of this InlineResponse2001.


        :param rm_id: The rm_id of this InlineResponse2001.
        :type rm_id: str
        """

        self._rm_id = rm_id

    @property
    def available(self) -> bool:
        """Gets the available of this InlineResponse2001.


        :return: The available of this InlineResponse2001.
        :rtype: bool
        """
        return self._available

    @available.setter
    def available(self, available: bool):
        """Sets the available of this InlineResponse2001.


        :param available: The available of this InlineResponse2001.
        :type available: bool
        """

        self._available = available
