# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2003Config(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, n: int=None):  # noqa: E501
        """InlineResponse2003Config - a model defined in Swagger

        :param n: The n of this InlineResponse2003Config.  # noqa: E501
        :type n: int
        """
        self.swagger_types = {
            'n': int
        }

        self.attribute_map = {
            'n': 'n'
        }

        self._n = n

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2003Config':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_3_config of this InlineResponse2003Config.  # noqa: E501
        :rtype: InlineResponse2003Config
        """
        return util.deserialize_model(dikt, cls)

    @property
    def n(self) -> int:
        """Gets the n of this InlineResponse2003Config.


        :return: The n of this InlineResponse2003Config.
        :rtype: int
        """
        return self._n

    @n.setter
    def n(self, n: int):
        """Sets the n of this InlineResponse2003Config.


        :param n: The n of this InlineResponse2003Config.
        :type n: int
        """

        self._n = n
