# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.inline_response2003_config import InlineResponse2003Config  # noqa: F401,E501
from swagger_server.models.inline_response2003_impl import InlineResponse2003Impl  # noqa: F401,E501
from swagger_server import util


class InlineResponse2005(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, impl: InlineResponse2003Impl=None, config: InlineResponse2003Config=None, coefs: List[float]=None):  # noqa: E501
        """InlineResponse2005 - a model defined in Swagger

        :param impl: The impl of this InlineResponse2005.  # noqa: E501
        :type impl: InlineResponse2003Impl
        :param config: The config of this InlineResponse2005.  # noqa: E501
        :type config: InlineResponse2003Config
        :param coefs: The coefs of this InlineResponse2005.  # noqa: E501
        :type coefs: List[float]
        """
        self.swagger_types = {
            'impl': InlineResponse2003Impl,
            'config': InlineResponse2003Config,
            'coefs': List[float]
        }

        self.attribute_map = {
            'impl': 'impl',
            'config': 'config',
            'coefs': 'coefs'
        }

        self._impl = impl
        self._config = config
        self._coefs = coefs

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2005':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_5 of this InlineResponse2005.  # noqa: E501
        :rtype: InlineResponse2005
        """
        return util.deserialize_model(dikt, cls)

    @property
    def impl(self) -> InlineResponse2003Impl:
        """Gets the impl of this InlineResponse2005.


        :return: The impl of this InlineResponse2005.
        :rtype: InlineResponse2003Impl
        """
        return self._impl

    @impl.setter
    def impl(self, impl: InlineResponse2003Impl):
        """Sets the impl of this InlineResponse2005.


        :param impl: The impl of this InlineResponse2005.
        :type impl: InlineResponse2003Impl
        """

        self._impl = impl

    @property
    def config(self) -> InlineResponse2003Config:
        """Gets the config of this InlineResponse2005.


        :return: The config of this InlineResponse2005.
        :rtype: InlineResponse2003Config
        """
        return self._config

    @config.setter
    def config(self, config: InlineResponse2003Config):
        """Sets the config of this InlineResponse2005.


        :param config: The config of this InlineResponse2005.
        :type config: InlineResponse2003Config
        """

        self._config = config

    @property
    def coefs(self) -> List[float]:
        """Gets the coefs of this InlineResponse2005.


        :return: The coefs of this InlineResponse2005.
        :rtype: List[float]
        """
        return self._coefs

    @coefs.setter
    def coefs(self, coefs: List[float]):
        """Sets the coefs of this InlineResponse2005.


        :param coefs: The coefs of this InlineResponse2005.
        :type coefs: List[float]
        """

        self._coefs = coefs
