# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, rm_id: str=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param rm_id: The rm_id of this InlineResponse200.  # noqa: E501
        :type rm_id: str
        """
        self.swagger_types = {
            'rm_id': str
        }

        self.attribute_map = {
            'rm_id': 'rmId'
        }

        self._rm_id = rm_id

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def rm_id(self) -> str:
        """Gets the rm_id of this InlineResponse200.


        :return: The rm_id of this InlineResponse200.
        :rtype: str
        """
        return self._rm_id

    @rm_id.setter
    def rm_id(self, rm_id: str):
        """Sets the rm_id of this InlineResponse200.


        :param rm_id: The rm_id of this InlineResponse200.
        :type rm_id: str
        """

        self._rm_id = rm_id
