# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2004(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, task_name: str=None, impl_name: str=None, impl_rm: str=None):  # noqa: E501
        """InlineResponse2004 - a model defined in Swagger

        :param task_name: The task_name of this InlineResponse2004.  # noqa: E501
        :type task_name: str
        :param impl_name: The impl_name of this InlineResponse2004.  # noqa: E501
        :type impl_name: str
        :param impl_rm: The impl_rm of this InlineResponse2004.  # noqa: E501
        :type impl_rm: str
        """
        self.swagger_types = {
            'task_name': str,
            'impl_name': str,
            'impl_rm': str
        }

        self.attribute_map = {
            'task_name': 'taskName',
            'impl_name': 'implName',
            'impl_rm': 'implRM'
        }

        self._task_name = task_name
        self._impl_name = impl_name
        self._impl_rm = impl_rm

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2004':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_4 of this InlineResponse2004.  # noqa: E501
        :rtype: InlineResponse2004
        """
        return util.deserialize_model(dikt, cls)

    @property
    def task_name(self) -> str:
        """Gets the task_name of this InlineResponse2004.


        :return: The task_name of this InlineResponse2004.
        :rtype: str
        """
        return self._task_name

    @task_name.setter
    def task_name(self, task_name: str):
        """Sets the task_name of this InlineResponse2004.


        :param task_name: The task_name of this InlineResponse2004.
        :type task_name: str
        """

        self._task_name = task_name

    @property
    def impl_name(self) -> str:
        """Gets the impl_name of this InlineResponse2004.


        :return: The impl_name of this InlineResponse2004.
        :rtype: str
        """
        return self._impl_name

    @impl_name.setter
    def impl_name(self, impl_name: str):
        """Sets the impl_name of this InlineResponse2004.


        :param impl_name: The impl_name of this InlineResponse2004.
        :type impl_name: str
        """

        self._impl_name = impl_name

    @property
    def impl_rm(self) -> str:
        """Gets the impl_rm of this InlineResponse2004.


        :return: The impl_rm of this InlineResponse2004.
        :rtype: str
        """
        return self._impl_rm

    @impl_rm.setter
    def impl_rm(self, impl_rm: str):
        """Sets the impl_rm of this InlineResponse2004.


        :param impl_rm: The impl_rm of this InlineResponse2004.
        :type impl_rm: str
        """

        self._impl_rm = impl_rm
