# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.tasks_input_params import TasksInputParams  # noqa: F401,E501
from swagger_server import util


class InlineResponse2002(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, task_name: str=None, input_params: List[TasksInputParams]=None):  # noqa: E501
        """InlineResponse2002 - a model defined in Swagger

        :param task_name: The task_name of this InlineResponse2002.  # noqa: E501
        :type task_name: str
        :param input_params: The input_params of this InlineResponse2002.  # noqa: E501
        :type input_params: List[TasksInputParams]
        """
        self.swagger_types = {
            'task_name': str,
            'input_params': List[TasksInputParams]
        }

        self.attribute_map = {
            'task_name': 'taskName',
            'input_params': 'inputParams'
        }

        self._task_name = task_name
        self._input_params = input_params

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2002':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_2 of this InlineResponse2002.  # noqa: E501
        :rtype: InlineResponse2002
        """
        return util.deserialize_model(dikt, cls)

    @property
    def task_name(self) -> str:
        """Gets the task_name of this InlineResponse2002.


        :return: The task_name of this InlineResponse2002.
        :rtype: str
        """
        return self._task_name

    @task_name.setter
    def task_name(self, task_name: str):
        """Sets the task_name of this InlineResponse2002.


        :param task_name: The task_name of this InlineResponse2002.
        :type task_name: str
        """

        self._task_name = task_name

    @property
    def input_params(self) -> List[TasksInputParams]:
        """Gets the input_params of this InlineResponse2002.


        :return: The input_params of this InlineResponse2002.
        :rtype: List[TasksInputParams]
        """
        return self._input_params

    @input_params.setter
    def input_params(self, input_params: List[TasksInputParams]):
        """Sets the input_params of this InlineResponse2002.


        :param input_params: The input_params of this InlineResponse2002.
        :type input_params: List[TasksInputParams]
        """

        self._input_params = input_params
