# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.inline_response2003_config import InlineResponse2003Config  # noqa: F401,E501
from swagger_server.models.inline_response2003_impl import InlineResponse2003Impl  # noqa: F401,E501
from swagger_server import util


class InlineResponse2003(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, impl: InlineResponse2003Impl=None, config: InlineResponse2003Config=None):  # noqa: E501
        """InlineResponse2003 - a model defined in Swagger

        :param impl: The impl of this InlineResponse2003.  # noqa: E501
        :type impl: InlineResponse2003Impl
        :param config: The config of this InlineResponse2003.  # noqa: E501
        :type config: InlineResponse2003Config
        """
        self.swagger_types = {
            'impl': InlineResponse2003Impl,
            'config': InlineResponse2003Config
        }

        self.attribute_map = {
            'impl': 'impl',
            'config': 'config'
        }

        self._impl = impl
        self._config = config

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2003':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_3 of this InlineResponse2003.  # noqa: E501
        :rtype: InlineResponse2003
        """
        return util.deserialize_model(dikt, cls)

    @property
    def impl(self) -> InlineResponse2003Impl:
        """Gets the impl of this InlineResponse2003.


        :return: The impl of this InlineResponse2003.
        :rtype: InlineResponse2003Impl
        """
        return self._impl

    @impl.setter
    def impl(self, impl: InlineResponse2003Impl):
        """Sets the impl of this InlineResponse2003.


        :param impl: The impl of this InlineResponse2003.
        :type impl: InlineResponse2003Impl
        """

        self._impl = impl

    @property
    def config(self) -> InlineResponse2003Config:
        """Gets the config of this InlineResponse2003.


        :return: The config of this InlineResponse2003.
        :rtype: InlineResponse2003Config
        """
        return self._config

    @config.setter
    def config(self, config: InlineResponse2003Config):
        """Sets the config of this InlineResponse2003.


        :param config: The config of this InlineResponse2003.
        :type config: InlineResponse2003Config
        """

        self._config = config
