# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TasksexecuteInputParams(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, param: str=None, value: object=None):  # noqa: E501
        """TasksexecuteInputParams - a model defined in Swagger

        :param param: The param of this TasksexecuteInputParams.  # noqa: E501
        :type param: str
        :param value: The value of this TasksexecuteInputParams.  # noqa: E501
        :type value: object
        """
        self.swagger_types = {
            'param': str,
            'value': object
        }

        self.attribute_map = {
            'param': 'param',
            'value': 'value'
        }

        self._param = param
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'TasksexecuteInputParams':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tasksexecute_inputParams of this TasksexecuteInputParams.  # noqa: E501
        :rtype: TasksexecuteInputParams
        """
        return util.deserialize_model(dikt, cls)

    @property
    def param(self) -> str:
        """Gets the param of this TasksexecuteInputParams.


        :return: The param of this TasksexecuteInputParams.
        :rtype: str
        """
        return self._param

    @param.setter
    def param(self, param: str):
        """Sets the param of this TasksexecuteInputParams.


        :param param: The param of this TasksexecuteInputParams.
        :type param: str
        """

        self._param = param

    @property
    def value(self) -> object:
        """Gets the value of this TasksexecuteInputParams.


        :return: The value of this TasksexecuteInputParams.
        :rtype: object
        """
        return self._value

    @value.setter
    def value(self, value: object):
        """Sets the value of this TasksexecuteInputParams.


        :param value: The value of this TasksexecuteInputParams.
        :type value: object
        """

        self._value = value
